/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connexion.Connexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import services.InscriptionFormationService;

/**
 *
 * @author GIGA STORE
 */
public class NewJFrame1 extends javax.swing.JFrame {
    private Connexion connexion;

    private static JFreeChart createChart() {
         // Récupérer le dataset à partir du service
        InscriptionFormationService service = new InscriptionFormationService();
        CategoryDataset dataset = service.createDataset();

        // Création du graphique à barres
        JFreeChart chart = ChartFactory.createBarChart(
            "Nombre de participants par formation", // Titre mis à jour
            "Formation",
            "Nombre de participants",
            dataset
        );

        // Personnalisation du graphique (couleurs, police, etc.)
        chart.getCategoryPlot().setBackgroundPaint(java.awt.Color.LIGHT_GRAY);
        chart.getCategoryPlot().setRangeGridlinePaint(java.awt.Color.WHITE);

        return chart;
    }
        public CategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try (Connection conn = connexion.getCn()) {
            // Requête SQL pour récupérer le nombre d'inscriptions par formation
            String sql = "SELECT f.intitule, COUNT(i.participant_id) AS participants_count "
                       + "FROM inscriptionFormation i "
                       + "JOIN formation f ON i.formation_id = f.id "
                       + "GROUP BY f.intitule";

            // Exécution de la requête
            try (PreparedStatement stmt = conn.prepareStatement(sql);
                 ResultSet rs = stmt.executeQuery()) {

                // Ajouter les données récupérées dans le dataset
                while (rs.next()) {
                    String formationName = rs.getString("intitule");
                    int participantsCount = rs.getInt("participants_count");

                    // Ajouter les données dans le dataset (série = "Participants", catégorie = formationName)
                    dataset.addValue(participantsCount, "Participants", formationName);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw new RuntimeException("Erreur lors de la récupération des inscriptions", e);
        }

        return dataset;
    }
    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
           // Création et ajout du graphique
        ChartPanel chartPanel = new ChartPanel(createChart());
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 600)); // Taille initiale

       // Ajout du graphique au JFrame
        this.setLayout(new java.awt.BorderLayout());
        this.add(chartPanel, java.awt.BorderLayout.CENTER);
        // Affichage dans le JFrame
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   java.awt.EventQueue.invokeLater(() -> new NewJFrame1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
